Vagrant.configure("2") do |config|
  config.vm.define "node" do |node|
    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "node"
    node.vm.network "public_network", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter", mac: "08002710F69E"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    # node.vm.provision "shell", inline: <<-SHELL
    #   git clone https://github.com/faizan35/scripts_For_Help.git
    #   # Add your commands here
    # SHELL
  end
end
