Vagrant.configure("2") do |config|
  config.vm.define "node" do |node|
    node.vm.box = "bento/ubuntu-22.04"
    node.vm.hostname = "node"
    node.vm.network "public_network", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter", mac: "08002710F69E"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    node.vm.provision "shell", inline: <<-SHELL
      git clone https://github.com/faizan35/scripts_For_Help.git
      sudo ufw allow 22
      sudo ufw enable
      # Add your commands here
    SHELL
  end
end
