Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.hostname = "master"
    master.vm.network "public_network", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter", mac: "080027160697"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 4048
      vb.cpus = 4
    end
    master.vm.provision "shell", inline: <<-SHELL
      sudo ufw allow 22
      sudo ufw enable
      git clone https://github.com/faizan35/scripts_For_Help.git
      cd scripts_For_Help/k8s/minikube/
      cp install_minikube.sh /~
      cd ~
      chmod +x install_minikube.sh
      sudo rm -rf ~/scripts_For_Help/

    SHELL

    # master.vm.provision "file", source: "../scripts/", destination: "/home/vagrant/", run: "always"
  end
end
